from airflow.models import Variable

# Global
AIRFLOW_DAG_HOME = Variable.get("AIRFLOW_DAG_HOME", "/opt/airflow/dags/")
AIRFLOW_DAG_TMP = Variable.get("AIRFLOW_DAG_TMP", "/tmp/")
AIRFLOW_ENV = Variable.get("AIRFLOW_ENV", "dev")
AIRFLOW_URL = Variable.get("AIRFLOW_URL", "")

# Datagouv
DATAGOUV_SECRET_API_KEY = Variable.get("DATAGOUV_SECRET_API_KEY", "")
DEMO_DATAGOUV_SECRET_API_KEY = Variable.get("DEMO_DATAGOUV_SECRET_API_KEY", "")
FILES_BASE_URL = Variable.get("FILES_BASE_URL", "")

# Mattermost
MATTERMOST_DATAGOUV_DATAENG = Variable.get("MATTERMOST_DATAGOUV_DATAENG", "")
MATTERMOST_DATAGOUV_DATAENG_TEST = Variable.get("MATTERMOST_DATAGOUV_DATAENG_TEST", "")
MATTERMOST_DATAGOUV_EDITO = Variable.get("MATTERMOST_DATAGOUV_EDITO", "")
MATTERMOST_DATAGOUV_MOISSONNAGE = Variable.get("MATTERMOST_DATAGOUV_MOISSONNAGE", "")
MATTERMOST_DATAGOUV_ACTIVITES = Variable.get("MATTERMOST_DATAGOUV_ACTIVITES", "")
MATTERMOST_DATAGOUV_REPORTING = Variable.get("MATTERMOST_DATAGOUV_REPORTING", "")
MATTERMOST_TMPAPIGOUV = Variable.get("MATTERMOST_TMPAPIGOUV", "")
MATTERMOST_DATAGOUV_SCHEMA_ACTIVITE = Variable.get(
    "MATTERMOST_DATAGOUV_SCHEMA_ACTIVITE", ""
)
MATTERMOST_MODERATION_NOUVEAUTES = Variable.get("MATTERMOST_MODERATION_NOUVEAUTES", "")
MATTERMOST_DATAGOUV_TEAM = Variable.get("MATTERMOST_DATAGOUV_TEAM", "")
MATTERMOST_DATASERVICES_ONLY = Variable.get("MATTERMOST_DATASERVICES_ONLY", "")
MATTERMOST_SIMPLIFIONS_WEBHOOK_URL = Variable.get(
    "MATTERMOST_SIMPLIFIONS_WEBHOOK_URL", ""
)

# Minio
MINIO_URL = Variable.get("MINIO_URL", "object.files.data.gouv.fr")
MINIO_BUCKET_DATA_PIPELINE = Variable.get("MINIO_BUCKET_DATA_PIPELINE", "")
MINIO_BUCKET_DATA_PIPELINE_OPEN = Variable.get("MINIO_BUCKET_DATA_PIPELINE_OPEN", "")
MINIO_BUCKET_INFRA = Variable.get("MINIO_BUCKET_INFRA", "")
SECRET_MINIO_DATA_PIPELINE_USER = Variable.get("SECRET_MINIO_DATA_PIPELINE_USER", "")
SECRET_MINIO_DATA_PIPELINE_PASSWORD = Variable.get(
    "SECRET_MINIO_DATA_PIPELINE_PASSWORD", ""
)
MINIO_BUCKET_PNT = Variable.get("MINIO_BUCKET_PNT", "")
SECRET_MINIO_PNT_USER = Variable.get("SECRET_MINIO_PNT_USER", "")
SECRET_MINIO_PNT_PASSWORD = Variable.get("SECRET_MINIO_PNT_PASSWORD", "")
SECRET_MINIO_METEO_PE_USER = Variable.get("SECRET_MINIO_METEO_PE_USER", "")
SECRET_MINIO_METEO_PE_PASSWORD = Variable.get("SECRET_MINIO_METEO_PE_PASSWORD", "")

# INSEE
INSEE_BASE_URL = Variable.get("INSEE_BASE_URL", "")
SECRET_INSEE_LOGIN = Variable.get("SECRET_INSEE_LOGIN", "")
SECRET_INSEE_PASSWORD = Variable.get("SECRET_INSEE_PASSWORD", "")
SECRET_INSEE_BEARER = Variable.get("SECRET_INSEE_BEARER", "")

# INPI
SECRET_INPI_USER = Variable.get("SECRET_INPI_USER", "")
SECRET_INPI_PASSWORD = Variable.get("SECRET_INPI_PASSWORD", "")

# Twitter
TWITTER_CONSUMER_KEY = Variable.get("TWITTER_CONSUMER_KEY", "")
TWITTER_CONSUMER_KEY_SECRET = Variable.get("TWITTER_CONSUMER_KEY_SECRET", "")
TWITTER_ACCESS_TOKEN = Variable.get("TWITTER_ACCESS_TOKEN", "")
TWITTER_SECRET_TOKEN = Variable.get("TWITTER_SECRET_TOKEN", "")

# emails
SECRET_MAIL_DATAGOUV_BOT_USER = Variable.get("SECRET_MAIL_DATAGOUV_BOT_USER", "")
SECRET_MAIL_DATAGOUV_BOT_PASSWORD = Variable.get(
    "SECRET_MAIL_DATAGOUV_BOT_PASSWORD", ""
)
SECRET_MAIL_DATAGOUV_BOT_RECIPIENTS_PROD = Variable.get(
    "SECRET_MAIL_DATAGOUV_BOT_RECIPIENTS_PROD", ""
).split(",")

# meteo
SECRET_FTP_METEO_USER = Variable.get("SECRET_FTP_METEO_USER", "")
SECRET_FTP_METEO_PASSWORD = Variable.get("SECRET_FTP_METEO_PASSWORD", "")
SECRET_FTP_METEO_ADDRESS = Variable.get("SECRET_FTP_METEO_ADDRESS", "")
METEO_PNT_APPLICATION_ID = Variable.get("METEO_PNT_APPLICATION_ID", "")

# notion
SECRET_NOTION_KEY_IMPACT = Variable.get("SECRET_NOTION_KEY_IMPACT", "")

# grist
GRIST_API_URL = Variable.get("GRIST_API_URL", "")
SECRET_GRIST_API_KEY = Variable.get("SECRET_GRIST_API_KEY", "")

# sentry
SECRET_SENTRY_API_TOKEN = Variable.get("SECRET_SENTRY_API_TOKEN", "")
SENTRY_BASE_URL = Variable.get("SENTRY_BASE_URL", "")

# ssh
SECRET_SFTP_HOST = Variable.get("SECRET_SFTP_HOST", "")

# crisp
CRISP_WEBSITE_ID = Variable.get("CRISP_WEBSITE_ID", "")
CRISP_PLUGIN_ID = Variable.get("CRISP_PLUGIN_ID", "")
CRISP_PLUGIN_TOKEN = Variable.get("CRISP_PLUGIN_TOKEN", "")
CRISP_USER_ID = Variable.get("CRISP_USER_ID", "")
CRISP_USER_TOKEN = Variable.get("CRISP_USER_TOKEN", "")

# matomo
MATOMO_TOKEN = Variable.get("MATOMO_TOKEN", "")
