from airflow.models import Variable

# Global
AIRFLOW_DAG_HOME = Variable.get("AIRFLOW_DAG_HOME")
AIRFLOW_DAG_TMP = Variable.get('AIRFLOW_DAG_TMP')
AIRFLOW_ENV = Variable.get("AIRFLOW_ENV")

# Datagouv
DATAGOUV_SECRET_API_KEY = Variable.get("DATAGOUV_SECRET_API_KEY")
FILES_BASE_URL = Variable.get('FILES_BASE_URL')

# Mattermost
MATTERMOST_DATAGOUV_DATAENG = Variable.get("MATTERMOST_DATAGOUV_DATAENG")
MATTERMOST_DATAGOUV_DATAENG_TEST = Variable.get("MATTERMOST_DATAGOUV_DATAENG_TEST")
MATTERMOST_DATAGOUV_EDITO = Variable.get('MATTERMOST_DATAGOUV_EDITO')

# Minio
MINIO_URL = Variable.get("MINIO_URL")
MINIO_BUCKET_DATA_PIPELINE = Variable.get("MINIO_BUCKET_DATA_PIPELINE")
SECRET_MINIO_DATA_PIPELINE_USER = Variable.get("SECRET_MINIO_DATA_PIPELINE_USER")
SECRET_MINIO_DATA_PIPELINE_PASSWORD = Variable.get("SECRET_MINIO_DATA_PIPELINE_PASSWORD")

# INSEE
INSEE_BASE_URL = Variable.get("INSEE_BASE_URL")
SECRET_INSEE_LOGIN = Variable.get('SECRET_INSEE_LOGIN')
SECRET_INSEE_PASSWORD = Variable.get('SECRET_INSEE_PASSWORD')

# INPI
SECRET_INPI_USER = Variable.get("SECRET_INPI_USER")
SECRET_INPI_PASSWORD = Variable.get("SECRET_INPI_PASSWORD")

# Twitter
TWITTER_CONSUMER_KEY = Variable.get('TWITTER_CONSUMER_KEY')
TWITTER_CONSUMER_KEY_SECRET = Variable.get('TWITTER_CONSUMER_KEY_SECRET')
TWITTER_ACCESS_TOKEN = Variable.get('TWITTER_ACCESS_TOKEN')
TWITTER_SECRET_TOKEN = Variable.get('TWITTER_SECRET_TOKEN')
MATTERMOST_EDITO_URL = Variable.get('MATTERMOST_DATAGOUV_EDITO')
