SCOPES = ["general", "candidats"]

dtypes: dict[str, dict[str, str]] = {
    "general": {
        "id_election": "VARCHAR",
        "id_brut_miom": "VARCHAR",
        "code_departement": "VARCHAR",
        "libelle_departement": "VARCHAR",
        "code_canton": "VARCHAR",
        "libelle_canton": "VARCHAR",
        "code_commune": "VARCHAR",
        "libelle_commune": "VARCHAR",
        "code_circonscription": "VARCHAR",
        "libelle_circonscription": "VARCHAR",
        "code_bv": "VARCHAR",
        "inscrits": "INT32",
        "abstentions": "INT32",
        "votants": "INT32",
        "blancs": "INT32",
        "nuls": "INT32",
        "exprimes": "INT32",
        "ratio_abstentions_inscrits": "FLOAT",
        "ratio_votants_inscrits": "FLOAT",
        "ratio_blancs_inscrits": "FLOAT",
        "ratio_blancs_votants": "FLOAT",
        "ratio_nuls_inscrits": "FLOAT",
        "ratio_nuls_votants": "FLOAT",
        "ratio_exprimes_inscrits": "FLOAT",
        "ratio_exprimes_votants": "FLOAT",
    },
    "candidats": {
        "id_election": "VARCHAR",
        "id_brut_miom": "VARCHAR",
        "code_departement": "VARCHAR",
        "code_commune": "VARCHAR",
        "code_bv": "VARCHAR",
        "no_panneau": "INT32",
        "voix": "INT32",
        "ratio_voix_inscrits": "FLOAT",
        "ratio_voix_exprimes": "FLOAT",
        "nuance": "VARCHAR",
        "sexe": "VARCHAR",
        "nom": "VARCHAR",
        "prenom": "VARCHAR",
        "libelle_abrege_liste": "VARCHAR",
        "libelle_etendu_liste": "VARCHAR",
        "nom_tete_liste": "VARCHAR",
        "binome": "VARCHAR",
    },
    "nuances": {
        "id_election": "VARCHAR",
        "type_nuance": "VARCHAR",
        "bloc": "VARCHAR",
        "libelle_nuance": "VARCHAR",
        "signification": "VARCHAR",
        "commentaires": "VARCHAR",
        "source": "VARCHAR",
    },
    "communes": {
        "id_election": "VARCHAR",
        "code_departement": "VARCHAR",
        "code_commune": "VARCHAR",
        "libelle_commune": "VARCHAR",
        "code_commune_actuel": "VARCHAR",
        "libelle_commune_actuel": "VARCHAR",
        "nb_communes_actuelles": "INT32",
        "methode_rapprochement": "VARCHAR",
        "millesime_cog_election": "INT32",
    },
}
