version: 2.1

jobs:
  clone-stack:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
        name: Clone stack
        command: |
          git clone https://github.com/datagouv/data-engineering-stack.git
  check-dags:
    docker:
      - image: apache/airflow:2.10.5-python3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r datagouv/data-engineering-stack/requirements.txt
      - run:
          name: Check DAGs
          command: |
            source venv/bin/activate
            airflow dags check

workflows:
  version: 2
  test-dags:
    jobs:
      - clone-stack
      - check-dags:
          requires:
            - clone-stack