DO $$
BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'base_mens' AND TABLE_SCHEMA = 'meteo') THEN
        CREATE UNLOGGED TABLE meteo.base_mens (
            NUM_POSTE VARCHAR,
            NOM_USUEL VARCHAR,
            LAT FLOAT,
            LON FLOAT,
            ALTI INT,
            AAAAMM VARCHAR,
            RR FLOAT NULL,
            QRR FLOAT NULL,
            NBRR FLOAT NULL,
            RR_ME FLOAT NULL,
            RRAB FLOAT NULL,
            QRRAB FLOAT NULL,
            RRABDAT FLOAT NULL,
            NBJRR1 FLOAT NULL,
            NBJRR5 FLOAT NULL,
            NBJRR10 FLOAT NULL,
            NBJRR30 FLOAT NULL,
            NBJRR50 FLOAT NULL,
            NBJRR100 FLOAT NULL,
            PMERM FLOAT NULL,
            QPMERM FLOAT NULL,
            NBPMERM FLOAT NULL,
            PMERMINAB FLOAT NULL,
            QPMERMINAB FLOAT NULL,
            PMERMINABDAT FLOAT NULL,
            TX FLOAT NULL,
            QTX FLOAT NULL,
            NBTX FLOAT NULL,
            TX_ME FLOAT NULL,
            TXAB FLOAT NULL,
            QTXAB FLOAT NULL,
            TXDAT FLOAT NULL,
            TXMIN FLOAT NULL,
            QTXMIN FLOAT NULL,
            TXMINDAT FLOAT NULL,
            NBJTX0 FLOAT NULL,
            NBJTX25 FLOAT NULL,
            NBJTX30 FLOAT NULL,
            NBJTX35 FLOAT NULL,
            NBJTXI20 FLOAT NULL,
            NBJTXI27 FLOAT NULL,
            NBJTXS32 FLOAT NULL,
            TN FLOAT NULL,
            QTN FLOAT NULL,
            NBTN FLOAT NULL,
            TN_ME FLOAT NULL,
            TNAB FLOAT NULL,
            QTNAB FLOAT NULL,
            TNDAT FLOAT NULL,
            TNMAX FLOAT NULL,
            QTNMAX FLOAT NULL,
            TNMAXDAT FLOAT NULL,
            NBJTN5 FLOAT NULL,
            NBJTN10 FLOAT NULL,
            NBJTNI10 FLOAT NULL,
            NBJTNI15 FLOAT NULL,
            NBJTNI20 FLOAT NULL,
            NBJTNS20 FLOAT NULL,
            NBJTNS25 FLOAT NULL,
            NBJGELEE FLOAT NULL,
            TAMPLIM FLOAT NULL,
            QTAMPLIM FLOAT NULL,
            TAMPLIAB FLOAT NULL,
            QTAMPLIAB FLOAT NULL,
            TAMPLIABDAT FLOAT NULL,
            NBTAMPLI FLOAT NULL,
            TM FLOAT NULL,
            QTM FLOAT NULL,
            NBTM FLOAT NULL,
            TMM FLOAT NULL,
            QTMM FLOAT NULL,
            NBTMM FLOAT NULL,
            NBJTMS24 FLOAT NULL,
            TMMIN FLOAT NULL,
            QTMMIN FLOAT NULL,
            TMMINDAT FLOAT NULL,
            TMMAX FLOAT NULL,
            QTMMAX FLOAT NULL,
            TMMAXDAT FLOAT NULL,
            UNAB FLOAT NULL,
            QUNAB FLOAT NULL,
            UNABDAT FLOAT NULL,
            NBUN FLOAT NULL,
            UXAB FLOAT NULL,
            QUXAB FLOAT NULL,
            UXABDAT FLOAT NULL,
            NBUX FLOAT NULL,
            UMM FLOAT NULL,
            QUMM FLOAT NULL,
            NBUM FLOAT NULL,
            TSVM FLOAT NULL,
            QTSVM FLOAT NULL,
            NBTSVM FLOAT NULL,
            ETP FLOAT NULL,
            QETP FLOAT NULL,
            FXIAB FLOAT NULL,
            QFXIAB FLOAT NULL,
            DXIAB FLOAT NULL,
            QDXIAB FLOAT NULL,
            FXIDAT FLOAT NULL,
            NBJFF10 FLOAT NULL,
            NBJFF16 FLOAT NULL,
            NBJFF28 FLOAT NULL,
            NBFXI FLOAT NULL,
            FXI3SAB FLOAT NULL,
            QFXI3SAB FLOAT NULL,
            DXI3SAB FLOAT NULL,
            QDXI3SAB FLOAT NULL,
            FXI3SDAT FLOAT NULL,
            NBJFXI3S10 FLOAT NULL,
            NBJFXI3S16 FLOAT NULL,
            NBJFXI3S28 FLOAT NULL,
            NBFXI3S FLOAT NULL,
            FXYAB FLOAT NULL,
            QFXYAB FLOAT NULL,
            DXYAB FLOAT NULL,
            QDXYAB FLOAT NULL,
            FXYABDAT FLOAT NULL,
            NBJFXY8 FLOAT NULL,
            NBJFXY10 FLOAT NULL,
            NBJFXY15 FLOAT NULL,
            NBFXY FLOAT NULL,
            FFM FLOAT NULL,
            QFFM FLOAT NULL,
            NBFFM FLOAT NULL,
            INST FLOAT NULL,
            QINST FLOAT NULL,
            NBINST FLOAT NULL,
            NBSIGMA0 FLOAT NULL,
            NBSIGMA20 FLOAT NULL,
            NBSIGMA80 FLOAT NULL,
            GLOT FLOAT NULL,
            QGLOT FLOAT NULL,
            NBGLOT FLOAT NULL,
            DIFT FLOAT NULL,
            QDIFT FLOAT NULL,
            NBDIFT FLOAT NULL,
            DIRT FLOAT NULL,
            QDIRT FLOAT NULL,
            NBDIRT FLOAT NULL,
            HNEIGEFTOT FLOAT NULL,
            QHNEIGEFTOT FLOAT NULL,
            HNEIGEFAB FLOAT NULL,
            QHNEIGEFAB FLOAT NULL,
            HNEIGEFDAT FLOAT NULL,
            NBHNEIGEF FLOAT NULL,
            NBJNEIG FLOAT NULL,
            NBJHNEIGEF1 FLOAT NULL,
            NBJHNEIGEF5 FLOAT NULL,
            NBJHNEIGEF10 FLOAT NULL,
            NBJSOLNG FLOAT NULL,
            NEIGETOTM FLOAT NULL,
            QNEIGETOTM FLOAT NULL,
            NEIGETOTAB FLOAT NULL,
            QNEIGETOTAB FLOAT NULL,
            NEIGETOTABDAT FLOAT NULL,
            NBJNEIGETOT1 FLOAT NULL,
            NBJNEIGETOT10 FLOAT NULL,
            NBJNEIGETOT30 FLOAT NULL,
            NBJGREL FLOAT NULL,
            NBJORAG FLOAT NULL,
            NBJBROU FLOAT,
            DEP VARCHAR
        );
    END IF;


    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'base_quot_vent' AND TABLE_SCHEMA = 'meteo') THEN
        CREATE UNLOGGED TABLE meteo.base_quot_vent (
            NUM_POSTE VARCHAR,
            NOM_USUEL VARCHAR,
            LAT FLOAT,
            LON FLOAT,
            ALTI INT,
            AAAAMMJJ VARCHAR,
            RR FLOAT NULL,
            QRR FLOAT NULL,
            TN FLOAT NULL,
            QTN FLOAT NULL,
            HTN FLOAT NULL,
            QHTN FLOAT NULL,
            TX FLOAT NULL,
            QTX FLOAT NULL,
            HTX FLOAT NULL,
            QHTX FLOAT NULL,
            TM FLOAT NULL,
            QTM FLOAT NULL,
            TNTXM FLOAT NULL,
            QTNTXM FLOAT NULL,
            TAMPLI FLOAT NULL,
            QTAMPLI FLOAT NULL,
            TNSOL FLOAT NULL,
            QTNSOL FLOAT NULL,
            TN50 FLOAT NULL,
            QTN50 FLOAT NULL,
            DG FLOAT NULL,
            QDG FLOAT NULL,
            FFM FLOAT NULL,
            QFFM FLOAT NULL,
            FF2M FLOAT NULL,
            QFF2M FLOAT NULL,
            FXY FLOAT NULL,
            QFXY FLOAT NULL,
            DXY FLOAT NULL,
            QDXY FLOAT NULL,
            HXY FLOAT NULL,
            QHXY FLOAT NULL,
            FXI FLOAT NULL,
            QFXI FLOAT NULL,
            DXI FLOAT NULL,
            QDXI FLOAT NULL,
            HXI FLOAT NULL,
            QHXI FLOAT NULL,
            FXI2 FLOAT NULL,
            QFXI2 FLOAT NULL,
            DXI2 FLOAT NULL,
            QDXI2 FLOAT NULL,
            HXI2 FLOAT NULL,
            QHXI2 FLOAT NULL,
            FXI3S FLOAT NULL,
            QFXI3S FLOAT NULL,
            DXI3S FLOAT NULL,
            QDXI3S FLOAT NULL,
            HXI3S FLOAT NULL,
            QHXI3S FLOAT NULL,
            DRR FLOAT NULL,
            QDRR FLOAT NULL,
            DEP VARCHAR
        );
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'base_quot_autres' AND TABLE_SCHEMA = 'meteo') THEN
        CREATE UNLOGGED TABLE meteo.base_quot_autres (
            NUM_POSTE VARCHAR,
            NOM_USUEL VARCHAR,
            LAT FLOAT NULL,
            LON FLOAT NULL,
            ALTI INT NULL,
            AAAAMMJJ VARCHAR,
            DHUMEC FLOAT NULL,
            QDHUMEC FLOAT NULL,
            PMERM FLOAT NULL,
            QPMERM FLOAT NULL,
            PMERMIN FLOAT NULL,
            QPMERMIN FLOAT NULL,
            INST FLOAT NULL,
            QINST FLOAT NULL,
            GLOT FLOAT NULL,
            QGLOT FLOAT NULL,
            DIFT FLOAT NULL,
            QDIFT FLOAT NULL,
            DIRT FLOAT NULL,
            QDIRT FLOAT NULL,
            INFRART FLOAT NULL,
            QINFRART FLOAT NULL,
            UV FLOAT NULL,
            QUV FLOAT NULL,
            UV_INDICEX FLOAT NULL,
            QUV_INDICEX FLOAT NULL,
            SIGMA FLOAT NULL,
            QSIGMA FLOAT NULL,
            UN FLOAT NULL,
            QUN FLOAT NULL,
            HUN FLOAT NULL,
            QHUN FLOAT NULL,
            UX FLOAT NULL,
            QUX FLOAT NULL,
            HUX FLOAT NULL,
            QHUX FLOAT NULL,
            UM FLOAT NULL,
            QUM FLOAT NULL,
            DHUMI40 FLOAT NULL,
            QDHUMI40 FLOAT NULL,
            DHUMI80 FLOAT NULL,
            QDHUMI80 FLOAT NULL,
            TSVM FLOAT NULL,
            QTSVM FLOAT NULL,
            ETPMON FLOAT NULL,
            QETPMON FLOAT NULL,
            ETPGRILLE FLOAT NULL,
            QETPGRILLE FLOAT NULL,
            ECOULEMENTM FLOAT NULL,
            QECOULEMENTM FLOAT NULL,
            HNEIGEF FLOAT NULL,
            QHNEIGEF FLOAT NULL,
            NEIGETOTX FLOAT NULL,
            QNEIGETOTX FLOAT NULL,
            NEIGETOT06 FLOAT NULL,
            QNEIGETOT06 FLOAT NULL,
            NEIG FLOAT NULL,
            QNEIG FLOAT NULL,
            BROU FLOAT NULL,
            QBROU FLOAT NULL,
            ORAG FLOAT NULL,
            QORAG FLOAT NULL,
            GRESIL FLOAT NULL,
            QGRESIL FLOAT NULL,
            GRELE FLOAT NULL,
            QGRELE FLOAT NULL,
            ROSEE FLOAT NULL,
            QROSEE FLOAT NULL,
            VERGLAS FLOAT NULL,
            QVERGLAS FLOAT NULL,
            SOLNEIGE FLOAT NULL,
            QSOLNEIGE FLOAT NULL,
            GELEE FLOAT NULL,
            QGELEE FLOAT NULL,
            FUMEE FLOAT NULL,
            QFUMEE FLOAT NULL,
            BRUME FLOAT NULL,
            QBRUME FLOAT NULL,
            ECLAIR FLOAT NULL,
            QECLAIR FLOAT NULL,
            NB300 FLOAT NULL,
            QNB300 FLOAT NULL,
            BA300 FLOAT NULL,
            QBA300 FLOAT NULL,
            TMERMIN FLOAT NULL,
            QTMERMIN FLOAT NULL,
            TMERMAX FLOAT NULL,
            QTMERMAX FLOAT NULL,
            DEP VARCHAR
        );
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'base_decad' AND TABLE_SCHEMA = 'meteo') THEN
        CREATE UNLOGGED TABLE meteo.base_decad (
            NUM_POSTE VARCHAR,
            NOM_USUEL VARCHAR,
            LAT FLOAT NULL,
            LON FLOAT NULL,
            ALTI INT NULL,
            AAAAMM VARCHAR,
            NUM_DECADE INT NULL,
            RR FLOAT NULL,
            QRR FLOAT NULL,
            NBRR INT NULL,
            RRAB FLOAT NULL,
            QRRAB FLOAT NULL,
            RRABDAT FLOAT NULL,
            NBJRR1 FLOAT NULL,
            NBJRR5 FLOAT NULL,
            NBJRR10 FLOAT NULL,
            NBJRR30 FLOAT NULL,
            NBJRR50 FLOAT NULL,
            NBJRR100 FLOAT NULL,
            PMERM FLOAT NULL,
            QPMERM FLOAT NULL,
            NBPMERM INT NULL,
            PMERMINAB FLOAT NULL,
            QPMERMINAB FLOAT NULL,
            PMERMINABDAT FLOAT NULL,
            TX FLOAT NULL,
            QTX FLOAT NULL,
            NBTX INT NULL,
            TXAB FLOAT NULL,
            QTXAB FLOAT NULL,
            TXDAT FLOAT NULL,
            TXMIN FLOAT NULL,
            QTXMIN FLOAT NULL,
            TXMINDAT FLOAT NULL,
            NBJTX0 FLOAT NULL,
            NBJTX25 FLOAT NULL,
            NBJTX30 FLOAT NULL,
            NBJTX35 FLOAT NULL,
            NBJTXI20 FLOAT NULL,
            NBJTXI27 FLOAT NULL,
            NBJTXS32 FLOAT NULL,
            TN FLOAT NULL,
            QTN FLOAT NULL,
            NBTN INT NULL,
            TNAB FLOAT NULL,
            QTNAB FLOAT NULL,
            TNDAT FLOAT NULL,
            TNMAX FLOAT NULL,
            QTNMAX FLOAT NULL,
            TNMAXDAT FLOAT NULL,
            NBJTN5 FLOAT NULL,
            NBJTN10 FLOAT NULL,
            NBJTNI10 FLOAT NULL,
            NBJTNI15 FLOAT NULL,
            NBJTNI20 FLOAT NULL,
            NBJTNS20 FLOAT NULL,
            NBJTNS25 FLOAT NULL,
            NBJGELEE FLOAT NULL,
            TAMPLIM FLOAT NULL,
            QTAMPLIM FLOAT NULL,
            TAMPLIAB FLOAT NULL,
            QTAMPLIAB FLOAT NULL,
            TAMPLIABDAT FLOAT NULL,
            NBTAMPLI INT NULL,
            TM FLOAT NULL,
            QTM FLOAT NULL,
            NBTM INT NULL,
            TMM FLOAT NULL,
            QTMM FLOAT NULL,
            NBTMM INT NULL,
            NBJTMS24 FLOAT NULL,
            TMMIN FLOAT NULL,
            QTMMIN FLOAT NULL,
            TMMINDAT FLOAT NULL,
            TMMAX FLOAT NULL,
            QTMMAX FLOAT NULL,
            TMMAXDAT FLOAT NULL,
            UNAB FLOAT NULL,
            QUNAB FLOAT NULL,
            UNABDAT FLOAT NULL,
            NBUN INT NULL,
            UXAB FLOAT NULL,
            QUXAB FLOAT NULL,
            UXABDAT FLOAT NULL,
            NBUX INT NULL,
            UMM FLOAT NULL,
            QUMM FLOAT NULL,
            NBUM INT NULL,
            TSVM FLOAT NULL,
            QTSVM FLOAT NULL,
            NBTSVM INT NULL,
            FXIAB FLOAT NULL,
            QFXIAB FLOAT NULL,
            DXIAB FLOAT NULL,
            QDXIAB FLOAT NULL,
            FXIDAT FLOAT NULL,
            NBJFF10 FLOAT NULL,
            NBJFF16 FLOAT NULL,
            NBJFF28 FLOAT NULL,
            NBFXI INT NULL,
            FXI3SAB FLOAT NULL,
            QFXI3SAB FLOAT NULL,
            DXI3SAB FLOAT NULL,
            QDXI3SAB FLOAT NULL,
            FXI3SDAT FLOAT NULL,
            NBJFXI3S10 FLOAT NULL,
            NBJFXI3S16 FLOAT NULL,
            NBJFXI3S28 FLOAT NULL,
            NBFXI3S INT NULL,
            FXYAB FLOAT NULL,
            QFXYAB FLOAT NULL,
            DXYAB FLOAT NULL,
            QDXYAB FLOAT NULL,
            FXYABDAT FLOAT NULL,
            NBJFXY8 FLOAT NULL,
            NBJFXY10 FLOAT NULL,
            NBJFXY15 FLOAT NULL,
            NBFXY INT NULL,
            FFM FLOAT NULL,
            QFFM FLOAT NULL,
            NBFFM INT NULL,
            INST FLOAT NULL,
            QINST FLOAT NULL,
            NBINST INT NULL,
            NBSIGMA0 FLOAT NULL,
            NBSIGMA20 FLOAT NULL,
            NBSIGMA80 FLOAT NULL,
            GLOT FLOAT NULL,
            QGLOT FLOAT NULL,
            NBGLOT INT NULL,
            DIFT FLOAT NULL,
            QDIFT FLOAT NULL,
            NBDIFT INT NULL,
            DIRT FLOAT NULL,
            QDIRT FLOAT NULL,
            NBDIRT INT NULL,
            HNEIGEFTOT FLOAT NULL,
            QHNEIGEFTOT FLOAT NULL,
            HNEIGEFAB FLOAT NULL,
            QHNEIGEFAB FLOAT NULL,
            HNEIGEFDAT FLOAT NULL,
            NBHNEIGEF INT NULL,
            NBJNEIG FLOAT NULL,
            NBJHNEIGEF1 FLOAT NULL,
            NBJHNEIGEF5 FLOAT NULL,
            NBJHNEIGEF10 FLOAT NULL,
            NBJSOLNG FLOAT NULL,
            NEIGETOTM FLOAT NULL,
            QNEIGETOTM FLOAT NULL,
            NEIGETOTAB FLOAT NULL,
            QNEIGETOTAB FLOAT NULL,
            NEIGETOTABDAT FLOAT NULL,
            NBJNEIGETOT1 FLOAT NULL,
            NBJNEIGETOT10 FLOAT NULL,
            NBJNEIGETOT30 FLOAT NULL,
            NBGREL INT NULL,
            NBJORAG FLOAT NULL,
            NBJBROU FLOAT NULL,
            DEP VARCHAR
        );
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'base_hor' AND TABLE_SCHEMA = 'meteo') THEN
        CREATE UNLOGGED TABLE meteo.base_hor (
            NUM_POSTE VARCHAR,
            NOM_USUEL VARCHAR,
            LAT FLOAT NULL,
            LON FLOAT NULL,
            ALTI INT NULL,
            AAAAMMJJHH VARCHAR,
            RR1 FLOAT NULL,
            QRR1 FLOAT NULL,
            DRR1 FLOAT NULL,
            QDRR1 FLOAT NULL,
            FF FLOAT NULL,
            QFF FLOAT NULL,
            DD FLOAT NULL,
            QDD FLOAT NULL,
            FXY FLOAT NULL,
            QFXY FLOAT NULL,
            DXY FLOAT NULL,
            QDXY FLOAT NULL,
            HXY FLOAT NULL,
            QHXY FLOAT NULL,
            FXI FLOAT NULL,
            QFXI FLOAT NULL,
            DXI FLOAT NULL,
            QDXI FLOAT NULL,
            HXI FLOAT NULL,
            QHXI FLOAT NULL,
            FF2 FLOAT NULL,
            QFF2 FLOAT NULL,
            DD2 FLOAT NULL,
            QDD2 FLOAT NULL,
            FXI2 FLOAT NULL,
            QFXI2 FLOAT NULL,
            DXI2 FLOAT NULL,
            QDXI2 FLOAT NULL,
            HXI2 FLOAT NULL,
            QHXI2 FLOAT NULL,
            FXI3S FLOAT NULL,
            QFXI3S FLOAT NULL,
            DXI3S FLOAT NULL,
            QDXI3S FLOAT NULL,
            HFXI3S FLOAT NULL,
            QHFXI3S FLOAT NULL,
            T FLOAT NULL,
            QT FLOAT NULL,
            TD FLOAT NULL,
            QTD FLOAT NULL,
            TN FLOAT NULL,
            QTN FLOAT NULL,
            HTN FLOAT NULL,
            QHTN FLOAT NULL,
            TX FLOAT NULL,
            QTX FLOAT NULL,
            HTX FLOAT NULL,
            QHTX FLOAT NULL,
            DG FLOAT NULL,
            QDG FLOAT NULL,
            T10 FLOAT NULL,
            QT10 FLOAT NULL,
            T20 FLOAT NULL,
            QT20 FLOAT NULL,
            T50 FLOAT NULL,
            QT50 FLOAT NULL,
            T100 FLOAT NULL,
            QT100 FLOAT NULL,
            TNSOL FLOAT NULL,
            QTNSOL FLOAT NULL,
            TN50 FLOAT NULL,
            QTN50 FLOAT NULL,
            TCHAUSSEE FLOAT NULL,
            QTCHAUSSEE FLOAT NULL,
            DHUMEC FLOAT NULL,
            QDHUMEC FLOAT NULL,
            U FLOAT NULL,
            QU FLOAT NULL,
            UN FLOAT NULL,
            QUN FLOAT NULL,
            HUN FLOAT NULL,
            QHUN FLOAT NULL,
            UX FLOAT NULL,
            QUX FLOAT NULL,
            HUX FLOAT NULL,
            QHUX FLOAT NULL,
            DHUMI40 FLOAT NULL,
            QDHUMI40 FLOAT NULL,
            DHUMI80 FLOAT NULL,
            QDHUMI80 FLOAT NULL,
            TSV FLOAT NULL,
            QTSV FLOAT NULL,
            PMER FLOAT NULL,
            QPMER FLOAT NULL,
            PSTAT FLOAT NULL,
            QPSTAT FLOAT NULL,
            PMERMIN FLOAT NULL,
            QPERMIN FLOAT NULL,
            GEOP FLOAT NULL,
            QGEOP FLOAT NULL,
            N FLOAT NULL,
            QN FLOAT NULL,
            NBAS FLOAT NULL,
            QNBAS FLOAT NULL,
            CL FLOAT NULL,
            QCL FLOAT NULL,
            CM FLOAT NULL,
            QCM FLOAT NULL,
            CH FLOAT NULL,
            QCH FLOAT NULL,
            N1 FLOAT NULL,
            QN1 FLOAT NULL,
            C1 FLOAT NULL,
            QC1 FLOAT NULL,
            B1 FLOAT NULL,
            QB1 FLOAT NULL,
            N2 FLOAT NULL,
            QN2 FLOAT NULL,
            C2 FLOAT NULL,
            QC2 FLOAT NULL,
            B2 FLOAT NULL,
            QCB2 FLOAT NULL,
            N3 FLOAT NULL,
            QN3 FLOAT NULL,
            C3 FLOAT NULL,
            QC3 FLOAT NULL,
            B3 FLOAT NULL,
            QB3 FLOAT NULL,
            N4 FLOAT NULL,
            QN4 FLOAT NULL,
            C4 FLOAT NULL,
            QC4 FLOAT NULL,
            B4 FLOAT NULL,
            QB4 FLOAT NULL,
            VV FLOAT NULL,
            QVV FLOAT NULL,
            DVV200 FLOAT NULL,
            QDVV200 FLOAT NULL,
            WW FLOAT NULL,
            QWW FLOAT NULL,
            W1 FLOAT NULL,
            QW1 FLOAT NULL,
            W2 FLOAT NULL,
            QW2 FLOAT NULL,
            SOL FLOAT NULL,
            QSOL FLOAT NULL,
            SOLNG FLOAT NULL,
            QSOLNG FLOAT NULL,
            TMER FLOAT NULL,
            QTMER FLOAT NULL,
            VVMER FLOAT NULL,
            QVVMER FLOAT NULL,
            ETATMER FLOAT NULL,
            QETATMER FLOAT NULL,
            DIRHOULE FLOAT NULL,
            QDIRHOULE FLOAT NULL,
            HVAGUE FLOAT NULL,
            QHVAGUE FLOAT NULL,
            PVAGUE FLOAT NULL,
            QPVAGUE FLOAT NULL,
            HNEIGEF FLOAT NULL,
            QHNEIGEF FLOAT NULL,
            NEIGETOT FLOAT NULL,
            QNEIGETOT FLOAT NULL,
            TSNEIGE FLOAT NULL,
            QTSNEIGE FLOAT NULL,
            TUBENEIGE FLOAT NULL,
            QTUBENEIGE FLOAT NULL,
            HNEIGEFI3 FLOAT NULL,
            QHNEIGEFI3 FLOAT NULL,
            HNEIGEFI1 FLOAT NULL,
            QHNEIGEFI1 FLOAT NULL,
            ESNEIGE FLOAT NULL,
            QESNEIGE FLOAT NULL,
            CHARGENEIGE FLOAT NULL,
            QCHARGENEIGE FLOAT NULL,
            GLO FLOAT NULL,
            QGLO FLOAT NULL,
            GLO2 FLOAT NULL,
            QGLO2 FLOAT NULL,
            DIR FLOAT NULL,
            QDIR FLOAT NULL,
            DIR2 FLOAT NULL,
            QDIR2 FLOAT NULL,
            DIF FLOAT NULL,
            QDIF FLOAT NULL,
            DIF2 FLOAT NULL,
            QDIF2 FLOAT NULL,
            UV FLOAT NULL,
            QUV FLOAT NULL,
            UV2 FLOAT NULL,
            QUV2 FLOAT NULL,
            UV_INDICE FLOAT NULL,
            QUV_INDICE FLOAT NULL,
            INFRAR FLOAT NULL,
            QINFRAR FLOAT NULL,
            INFRAR2 FLOAT NULL,
            QINFRAR2 FLOAT NULL,
            INS FLOAT NULL,
            QINS FLOAT NULL,
            INS2 FLOAT NULL,
            QINS2 FLOAT NULL,
            TLAGON FLOAT NULL,
            QTLAGON FLOAT NULL,
            TVEGETAUX FLOAT NULL,
            QTVEGETAUX FLOAT NULL,
            ECOULEMENT FLOAT NULL,
            QECOULEMENT FLOAT NULL,
            DEP VARCHAR
        );
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'base_min' AND TABLE_SCHEMA = 'meteo') THEN
        CREATE UNLOGGED TABLE meteo.base_min (
            NUM_POSTE VARCHAR,
            NOM_USUEL VARCHAR,
            LAT FLOAT NULL,
            LON FLOAT NULL,
            ALTI INT NULL,
            AAAAMMJJHHMN VARCHAR,
            RR FLOAT NULL,
            QRR FLOAT NULL,
            DEP VARCHAR
        );
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'base_decadagro' AND TABLE_SCHEMA = 'meteo') THEN
        CREATE UNLOGGED TABLE meteo.base_decadagro (
            NUM_POSTE VARCHAR,
            NOM_USUEL VARCHAR,
            LAT FLOAT NULL,
            LON FLOAT NULL,
            ALTI INT NULL,
            AAAAMM VARCHAR,
            NUM_DECADE INT NULL,
            RR FLOAT NULL,
            CRR FLOAT NULL,
            TN FLOAT NULL,
            CTN FLOAT NULL,
            TX FLOAT NULL,
            CTX FLOAT NULL,
            FFM FLOAT NULL,
            CFFM FLOAT NULL,
            TSVM FLOAT NULL,
            CTSVM FLOAT NULL,
            INST FLOAT NULL,
            CINST FLOAT NULL,
            GLOT FLOAT NULL,
            CGLOT FLOAT NULL,
            ETP FLOAT NULL,
            DEP VARCHAR
        );
    END IF;

    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'dag_processed' AND TABLE_SCHEMA = 'meteo') THEN
        CREATE UNLOGGED TABLE meteo.dag_processed (
            processed VARCHAR(255)
        );
    END IF;
END $$;

-- Create indexes on DEP, NUM_POSTE, NOM_USUEL, and AAAAMM
CREATE INDEX IF NOT EXISTS idx_base_mens_dep ON meteo.base_mens (DEP);
CREATE INDEX IF NOT EXISTS idx_base_mens_num_poste ON meteo.base_mens (NUM_POSTE);
CREATE INDEX IF NOT EXISTS idx_base_mens_nom_usuel ON meteo.base_mens (NOM_USUEL);
CREATE INDEX IF NOT EXISTS idx_base_mens_year ON meteo.base_mens (substring(AAAAMM::text, 1, 4));

-- Create indexes on DEP, NUM_POSTE, NOM_USUEL, and AAAAMMJJ
CREATE INDEX IF NOT EXISTS idx_base_quot_vent_dep ON meteo.base_quot_vent (DEP);
CREATE INDEX IF NOT EXISTS idx_base_quot_vent_num_poste ON meteo.base_quot_vent (NUM_POSTE);
CREATE INDEX IF NOT EXISTS idx_base_quot_vent_nom_usuel ON meteo.base_quot_vent (NOM_USUEL);
CREATE INDEX IF NOT EXISTS idx_base_quot_vent_year ON meteo.base_quot_vent (substring(AAAAMMJJ::text, 1, 4));

-- Create indexes on DEP, NUM_POSTE, NOM_USUEL, and AAAAMMJJ
CREATE INDEX IF NOT EXISTS idx_base_quot_autres_dep ON meteo.base_quot_autres (DEP);
CREATE INDEX IF NOT EXISTS idx_base_quot_autres_num_poste ON meteo.base_quot_autres (NUM_POSTE);
CREATE INDEX IF NOT EXISTS idx_base_quot_autres_nom_usuel ON meteo.base_quot_autres (NOM_USUEL);
CREATE INDEX IF NOT EXISTS idx_base_quot_autres_year ON meteo.base_quot_autres (substring(AAAAMMJJ::text, 1, 4));

-- Create indexes on DEP, NUM_POSTE, NOM_USUEL, and AAAAMM
CREATE INDEX IF NOT EXISTS idx_base_decad_dep ON meteo.base_decad (DEP);
CREATE INDEX IF NOT EXISTS idx_base_decad_num_poste ON meteo.base_decad (NUM_POSTE);
CREATE INDEX IF NOT EXISTS idx_base_decad_nom_usuel ON meteo.base_decad (NOM_USUEL);
CREATE INDEX IF NOT EXISTS idx_base_decad_year ON meteo.base_decad (substring(AAAAMM::text, 1, 4));

-- Create indexes on DEP, NUM_POSTE, NOM_USUEL, and AAAAMMJJHH
CREATE INDEX IF NOT EXISTS idx_base_hor_dep ON meteo.base_hor (DEP);
CREATE INDEX IF NOT EXISTS idx_base_hor_num_poste ON meteo.base_hor (NUM_POSTE);
CREATE INDEX IF NOT EXISTS idx_base_hor_nom_usuel ON meteo.base_hor (NOM_USUEL);
CREATE INDEX IF NOT EXISTS idx_base_hor_year ON meteo.base_hor (substring(AAAAMMJJHH::text, 1, 4));

-- Create indexes on DEP, NUM_POSTE, NOM_USUEL, and AAAAMMJJHHMN
CREATE INDEX IF NOT EXISTS idx_base_min_dep ON meteo.base_min (DEP);
CREATE INDEX IF NOT EXISTS idx_base_min_num_poste ON meteo.base_min (NUM_POSTE);
CREATE INDEX IF NOT EXISTS idx_base_min_nom_usuel ON meteo.base_min (NOM_USUEL);
CREATE INDEX IF NOT EXISTS idx_base_min_year ON meteo.base_min (substring(AAAAMMJJHHMN::text, 1, 4));

-- Create indexes on DEP, NUM_POSTE, NOM_USUEL, and AAAAMM
CREATE INDEX IF NOT EXISTS idx_base_decadagro_dep ON meteo.base_decadagro (DEP);
CREATE INDEX IF NOT EXISTS idx_base_decadagro_num_poste ON meteo.base_decadagro (NUM_POSTE);
CREATE INDEX IF NOT EXISTS idx_base_decadagro_nom_usuel ON meteo.base_decadagro (NOM_USUEL);
CREATE INDEX IF NOT EXISTS idx_base_decadagro_year ON meteo.base_decadagro (substring(AAAAMM::text, 1, 4));