# This workflow runs tests for the simplifions module when files in that directory are modified
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run simplifions tests

on:
  pull_request:
    paths:
      - 'verticales/simplifions/**'

jobs:
  test-simplifions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Create virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        
    - name: Install test dependencies
      run: |
        pip install -r verticales/simplifions/tests/test-requirements.txt
        
    - name: Run simplifions tests
      run: |
        pytest verticales/simplifions/tests/ -s -v
